[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Music: Exploring the Role of Intelligent Technologies in the Creation and Performance of Music"
